### ISSUE TITLE
AngularAMD + angular-br-filters == :(

### ISSUE THREAD

**Issue by RafaelPlantard** [the-darc/angular-br-filters#7]
I am receiving this message: BrM is not defined

When I am trying use it, here:
{{ fornecedor.pessoa.documento_pessoa | brCnpj }}

**Comment by rafaelzomer** [comment]
I'm witg the same problem, you resolved this issue?

**Comment by assisrafael** [comment]
Pull Requests are welcome! =)

**Comment by guilhermepaula** [comment]
I'm with the same problem. I installed with bower but it adds:
```javascript
<script src="bower_components/angular-br-filters/src/filters.js"></script>
```
instead of:
```javascript
<script src="bower_components/angular-br-filters/release/angular-br-filters.js"></script>
```
Changing it works, but you can't run any bower command again. :-(

**Comment by vanessaschissato** [comment]
I`m having the same problem.

**Comment by guilhermepaula** [comment]
Waiting the acceptance of pull request https://github.com/the-darc/angular-br-filters/pull/11 to close this issue...

**Comment by lucassouza1** [comment]
While the pull request is not aproved, you can add an override in your own bower file
```
"overrides": {
    "angular-br-filters": {
      "main": [
        "release/angular-br-filters.js"
      ]
    }
  },
```
